#!/usr/bin/perl

use strict;
use warnings;

use COD::Algebra::Vector qw( matrix_vector_mul );
use COD::AtomProperties;
use COD::CIF::Data qw( get_cell );
use COD::Cell qw( vectors2cell );
use COD::Fractional qw( symop_fract_from_ortho );
use COD::SPGLib qw( get_sym_dataset );
use JSON;

my $symprec = 1e-5;

my $json = decode_json join '', <>;

for my $structure (@$json) {
    my $o2f = symop_fract_from_ortho( vectors2cell( @{$structure->{attributes}{lattice_vectors}} ) );
    my @coordinates = map { [ matrix_vector_mul( $o2f, $_ ) ] } @{$structure->{attributes}{cartesian_site_positions}};

    # TODO: Check actual "species", not their labels
    my @types = map { int $COD::AtomProperties::atoms{$_}->{atomic_number} }
                    @{$structure->{attributes}{species_at_sites}};

    my $symmetry = get_sym_dataset( $structure->{attributes}{lattice_vectors},
                                    \@coordinates,
                                    \@types,
                                    $symprec );

    use Data::Dumper;
    print Dumper $symmetry;
}
